@startuml

User_App -> WebRTC_GW: POST /peers \n{\n\tkey: "YOUR_API_KEY",\n\tdomain: "localhost",\n\tturn: true,\n\tpeer_id: "data_caller"\n}
WebRTC_GW --> User_App: 201 Created\n{\n\tcommand_type: "PEERS_CREATE", \n\tparams: {\n\t\tpeer_id: "data_caller", \n\t\ttoken: "pt-75a06119-4672-4666-8cd2-5d04a5067080"\n\t}\n}

WebRTC_GW -> SkyWay_Server: CREATE PEER
User_App -> WebRTC_GW: GET /peers/data_callee/events?\ntoken=pt-75a06119-4672-4666-8cd2-5d04a5067080
SkyWay_Server --> WebRTC_GW: SUCCESS\n(to bind peer id)
WebRTC_GW --> User_App: 200 OK\n{"event"=>"OPEN",\n\tparams: {\n\t\tpeer_id: "data_caller", \n\t\ttoken: "pt-75a06119-4672-4666-8cd2-5d04a5067080"\n\t}\n}

User_App -> WebRTC_GW: POST /data {}
WebRTC_GW --> User_App: 201 Created\n{\n\tdata_id: "da-6f640ff7-9388-4e89-82aa-1f350eb3af84",\n\tip_v4: "172.16.1.106",\n\t"port"=>50002\n}

User_App -> WebRTC_GW: POST /data/connections\n{\n\tpeer_id: "data_caller",\n\ttoken: "pt-75a06119-4672-4666-8cd2-5d04a5067080",\n\ttarget_id": "data_callee",\n\toptions:{\n\t\tserialization: "BINARY"\n\t},\n\tparams: {\n\t\tdata_id: "da-6f640ff7-9388-4e89-82aa-1f350eb3af84"\n\t},\n\tredirect_params: {\n\t\tip_v4: "172.16.1.105",\n\t\tport: 10001\n\t}\n}
WebRTC_GW --> User_App: 202 Accepted\n{\n\tcommand_type: "DATA_CONNECTION_CREATE", \n\tparams:{ \n\t\tdata_connection_id: "dc-9e74e631-d92f-457e-a9ad-007e87d2c202"\n\t}\n}

User_App -> WebRTC_GW: GET /data/connections\n/dc-9e74e631-d92f-457e-a9ad-007e87d2c202/events
WebRTC_GW --> User_App: 200 OK\n{\n\tevent: "OPEN"\n}

loop
User_App -> WebRTC_GW: send UDP data to 172.16.1.106:50002
WebRTC_GW -> Target_Peer: redirect data with DataChannel
Target_Peer -> WebRTC_GW: recv data with DataChannel
WebRTC_GW -> User_App: redirect data to 172.16.1.105:10001 with UDP
end

User_App -> WebRTC_GW: Delete /data/connections\n/dc-9e74e631-d92f-457e-a9ad-007e87d2c202
WebRTC_GW -> Target_Peer: Close DataChannel
WebRTC_GW -> WebRTC_GW: erase Data object
WebRTC_GW --> User_App: 204 No Content
User_App -> WebRTC_GW: Delete /peers/data_caller?\ntoken=pt-75a06119-4672-4666-8cd2-5d04a5067080
WebRTC_GW -> SkyWay_Server: disconnect
WebRTC_GW --> User_App: 204 No Content
@enduml
