@startuml

User_App -> WebRTC_GW: POST /peers \n{\n\tkey: "YOUR_API_KEY",\n\tdomain: "localhost", \n\tturn: true,\n\tpeer_id: "media_callee"\n\t}\n}
WebRTC_GW --> User_App: 201 Created\n{\n\tcommand_type: "PEERS_CREATE",\n\tparams: {\n\t\tpeer_id: "media_callee",\n\t\ttoken: "pt-83f1612e-6bdf-491d-b4fc-8ecf3d3cf953"\n\t}\n}

WebRTC_GW -> SkyWay_Server: CREATE PEER
User_App -> WebRTC_GW: GET /peers/media_callee/events?\ntoken=pt-83f1612e-6bdf-491d-b4fc-8ecf3d3cf953
SkyWay_Server --> WebRTC_GW: SUCCESS\n(to bind peer id)
WebRTC_GW --> User_App: 200 OK\n{\n\tevent: "OPEN",\n\tparams: {\n\t\tpeer_id: "media_callee",\n\t\ttoken: "pt-83f1612e-6bdf-491d-b4fc-8ecf3d3cf953"\n\t}\n}

User_App -> WebRTC_GW: POST  /media \n{\n\tis_video":true\n}
WebRTC_GW --> User_App: 201 Created\n{\n\tip_v4: "172.16.1.106",\n\tmedia_id: "vi-0b3ecb19-c255-482c-8e6c-3e4169813e6e",\n\tport: 50001\n}

User_App -> WebRTC_GW: POST  /media \n{\n\tis_video":false\n}
WebRTC_GW --> User_App: 201 Created\n{\n\tip_v4: "172.16.1.106",\n\tmedia_id: "au-53f271f7-e6ed-42a1-aa54-29853b4dc948",\n\tport: 50002\n}

User_App -> WebRTC_GW: GET /peers/media_callee/events?\ntoken=pt-83f1612e-6bdf-491d-b4fc-8ecf3d3cf953
WebRTC_GW --> User_App: 200 OK\n{\n\tcall_params: {\n\t\tmedia_connection_id: "mc-a5e9f6c5-76e6-4261-b80f-eb95497f2a83"\n\t},\n\tevent: "CALL",\n\tparams: {\n\t\tpeer_id: media_callee",\n\t\ttoken: "pt-83f1612e-6bdf-491d-b4fc-8ecf3d3cf953"\n\t}\n}

User_App -> WebRTC_GW: POST /media/connections\n/mc-a5e9f6c5-76e6-4261-b80f-eb95497f2a83/answer\n {\n\tconstraints: {\n\t\tvideo: true,\n\t\tvideoReceiveEnabled: true,\n\t\taudio: true,\n\t\taudioReceiveEnabled: true,\n\t\tvideo_params: {\n\t\t\tband_width: 1500,\n\t\t\tcodec: "H264",\n\t\t\tmedia_id: "vi-0b3ecb19-c255-482c-8e6c-3e4169813e6e",\n\t\t\tpayload_type: 100\n\t\t},\n\t\taudio_params: {\n\t\t\tband_width: 1500, \n\t\t\tcodec: "opus",\n\t\t\tmedia_id: "au-53f271f7-e6ed-42a1-aa54-29853b4dc948",\n\t\t\tpayload_type: 111\n\t\t}\n\t},\n\tredirect_params: {\n\t\tvideo: {\n\t\t\tip_v4: "127.0.0.1",\n\t\t\tport: 20000\n\t\t},\n\t\taudio: {\n\t\t\tip_v4: "127.0.0.1",\n\t\t\tport: 20001\n\t\t}\n\t}\n}
WebRTC_GW --> User_App: 202 Accepted\n{\n\tcommand_type: "MEDIA_CONNECTION_ANSWER",\n\tparams: {\n\t\taudio_id: "au-53f271f7-e6ed-42a1-aa54-29853b4dc948",\n\t\tvideo_id: "vi-0b3ecb19-c255-482c-8e6c-3e4169813e6e"\n\t}\n}

User_App -> WebRTC_GW: GET /media/connections\n/mc-a5e9f6c5-76e6-4261-b80f-eb95497f2a83/events
WebRTC_GW --> User_App: 200 OK\n{\n\tevent: "STREAM"\n}

loop
User_App -> WebRTC_GW: send RTP Video to 172.16.1.106:50001
WebRTC_GW -> Target_Peer: redirect Video with MediaStream
User_App -> WebRTC_GW: send RTP Audio to 172.16.1.106:50002
WebRTC_GW -> Target_Peer: redirect Audio with MediaStream
Target_Peer -> WebRTC_GW: recv Video with MediaStream
WebRTC_GW -> User_App: redirect RTP Video to 127.0.0.1:20000
Target_Peer -> WebRTC_GW: recv Audio with MediaStream
WebRTC_GW -> User_App: redirect RTP Audio to 127.0.0.1:20001
end

User_App -> WebRTC_GW: Delete /media/connections\n/mc-a5e9f6c5-76e6-4261-b80f-eb95497f2a83
WebRTC_GW -> Target_Peer: Close MediaStream
WebRTC_GW -> WebRTC_GW: erase Video object\n and Audio object
WebRTC_GW --> User_App: 204 No Content
User_App -> WebRTC_GW: Delete /peers/media_callee?\ntoken=pt-83f1612e-6bdf-491d-b4fc-8ecf3d3cf953
WebRTC_GW -> SkyWay_Server: disconnect
WebRTC_GW --> User_App: 204 No Content
@enduml
